namespace IgnaCheck.Domain.Entities;

/// <summary>
/// Represents an AI-detected compliance gap or finding for a specific control within a project.
/// This is the core output of the AI gap analysis engine.
/// </summary>
public class ComplianceFinding : BaseAuditableEntity, ITenantEntity
{
    /// <summary>
    /// Organization (tenant) that owns this finding.
    /// </summary>
    public Guid OrganizationId { get; set; }

    /// <summary>
    /// The project this finding belongs to.
    /// </summary>
    public Guid ProjectId { get; set; }

    /// <summary>
    /// The compliance control being assessed.
    /// </summary>
    public Guid ControlId { get; set; }

    /// <summary>
    /// Unique identifier for the finding (for tracking across analysis runs).
    /// </summary>
    public string FindingCode { get; set; } = string.Empty;

    /// <summary>
    /// Title or summary of the finding.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description of what's missing or non-compliant.
    /// Generated by AI with specific references to evidence (or lack thereof).
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Current compliance status of this control.
    /// </summary>
    public ComplianceStatus Status { get; set; } = ComplianceStatus.NotAssessed;

    /// <summary>
    /// Workflow status for tracking remediation progress.
    /// </summary>
    public FindingWorkflowStatus WorkflowStatus { get; set; } = FindingWorkflowStatus.Open;

    /// <summary>
    /// Risk level/severity of this finding.
    /// </summary>
    public RiskLevel RiskLevel { get; set; } = RiskLevel.Medium;

    /// <summary>
    /// AI-generated remediation recommendations.
    /// Plain-English guidance on how to address the gap.
    /// </summary>
    public string? RemediationGuidance { get; set; }

    /// <summary>
    /// Estimated effort to remediate (in hours or story points).
    /// Can be AI-suggested or manually adjusted.
    /// </summary>
    public decimal? EstimatedEffort { get; set; }

    /// <summary>
    /// AI confidence score (0.0 - 1.0) for this finding.
    /// Higher values indicate higher confidence in the assessment.
    /// </summary>
    public decimal? ConfidenceScore { get; set; }

    /// <summary>
    /// Source documents that were analyzed (references by Document IDs).
    /// Stored as JSON array of GUIDs.
    /// </summary>
    public string? SourceDocumentIds { get; set; }

    /// <summary>
    /// Specific text excerpts from documents that support this finding.
    /// Stored as JSON array of objects with {documentId, excerpt, pageNumber}.
    /// </summary>
    public string? EvidenceExcerpts { get; set; }

    /// <summary>
    /// Indicates whether a human has reviewed and validated this AI finding.
    /// </summary>
    public bool IsReviewed { get; set; }

    /// <summary>
    /// User who reviewed this finding.
    /// </summary>
    public string? ReviewedBy { get; set; }

    /// <summary>
    /// Date when this finding was reviewed.
    /// </summary>
    public DateTime? ReviewedDate { get; set; }

    /// <summary>
    /// Reviewer's comments or adjustments.
    /// </summary>
    public string? ReviewNotes { get; set; }

    /// <summary>
    /// Date when this finding should be resolved by.
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// User assigned to remediate this finding.
    /// </summary>
    public string? AssignedTo { get; set; }

    /// <summary>
    /// Date when this finding was resolved.
    /// </summary>
    public DateTime? ResolvedDate { get; set; }

    /// <summary>
    /// User who resolved this finding.
    /// </summary>
    public string? ResolvedBy { get; set; }

    /// <summary>
    /// Resolution notes explaining how the gap was addressed.
    /// </summary>
    public string? ResolutionNotes { get; set; }

    /// <summary>
    /// ID of the remediation task if one was created.
    /// </summary>
    public Guid? RemediationTaskId { get; set; }

    /// <summary>
    /// Date of the last AI re-analysis.
    /// </summary>
    public DateTime? LastAnalysisDate { get; set; }

    /// <summary>
    /// Version number of the AI analysis (incremented on each run).
    /// </summary>
    public int AnalysisVersion { get; set; } = 1;

    /// <summary>
    /// AI model used for this analysis (e.g., "gpt-4", "claude-3-sonnet").
    /// </summary>
    public string? AnalysisModel { get; set; }

    /// <summary>
    /// Raw AI response data (for debugging and audit trail).
    /// Stored as JSON.
    /// </summary>
    public string? RawAnalysisData { get; set; }

    // Navigation properties

    /// <summary>
    /// The organization this finding belongs to.
    /// </summary>
    public Organization Organization { get; set; } = null!;

    /// <summary>
    /// The project this finding belongs to.
    /// </summary>
    public Project Project { get; set; } = null!;

    /// <summary>
    /// The compliance control being assessed.
    /// </summary>
    public ComplianceControl Control { get; set; } = null!;

    /// <summary>
    /// Remediation task if one was created.
    /// </summary>
    public RemediationTask? RemediationTask { get; set; }

    /// <summary>
    /// Supporting evidence documents.
    /// </summary>
    public ICollection<FindingEvidence> Evidence { get; set; } = new List<FindingEvidence>();

    /// <summary>
    /// Comments and discussions on this finding.
    /// </summary>
    public ICollection<FindingComment> Comments { get; set; } = new List<FindingComment>();
}
